CREATE FUNCTION FNAPP_RE_GENERATECODE()
RETURNS GENERATEDCODE NVARCHAR(50) LANGUAGE SQLSCRIPT AS 
BEGIN

SELECT CONCAT(TO_NVARCHAR(
            ADD_SECONDS ( 
            TO_TIMESTAMP (
            TO_NVARCHAR( CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS:FF3')
                  ,'YYYY-MM-DD HH24:MI:SS:FF3')
                  , -60*5)
                  ,'YYMMDDHH24MISS.FF3'),LPAD (FLOOR(99*RAND()+1), 2, '0') )  INTO GENERATEDCODE  FROM DUMMY;
--SELECT CONCAT(GENERATEDCODE, LPAD (FLOOR(99*RAND()+1), 2, '0')) INTO GENERATEDCODE FROM DUMMY;
END